import Head from "next/head";

import WithIconBtn from "@/components/Buttons/WithIconBtn";
import Logo from "@/components/Header/Logo";
import Nav from "@/components/Header/Nav";

import Footer from "@/components/Footer/Footer";
import Solution from "@/components/SolutionBlock/Solution";
import Post from "@/components/PostBlock/Post";
import { useEffect, useRef, useState } from "react";
import ProfessionTeam from "@/components/ProfessionTeam/ProfessionTeam";
import Form from "@/components/Form/Form";
import BusinesCases from "@/components/BusinesCases/BusinesCases";
var throttle = require("lodash.throttle");

export default function Home() {
  const [isHeaderTransparent, setIsHeaderTransparent] = useState(true);
  const headerRef = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      if (window.pageYOffset > getHeaderHeight()) {
        setIsHeaderTransparent(false);
      } else {
        setIsHeaderTransparent(true);
      }
    };

    window.addEventListener("scroll", throttle(handleScroll, 100));

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const getHeaderHeight = () => {
    if (window.innerWidth >= 768) {
      return 70; // desktop header height
    } else {
      return 120; // mobile/tablet header height
    }
  };

  const headerStyle = {
    opacity: isHeaderTransparent ? 1 : 0.8,
    background: isHeaderTransparent ? "transparent" : "rgba(0, 0, 0, 0.25)",
  };
  return (
    <>
      <Head>
        <title>Land</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="main__photo" id="home">
        <header
          className=" container header"
          ref={headerRef}
          style={headerStyle}
        >
          <Logo></Logo>
          <Nav></Nav>
        </header>

        <section className="container hero">
          <h1 className="hero__title">The Sky Is The Limit</h1>
          <h2 className="hero__text">
            We provide world class financial assistance
          </h2>
          <WithIconBtn text="Read More"></WithIconBtn>
        </section>
      </div>

      <Solution></Solution>

      <BusinesCases></BusinesCases>

      <Post></Post>

      <ProfessionTeam></ProfessionTeam>
      <Form></Form>

      <Footer></Footer>
    </>
  );
}
